##docker-compose.yaml

services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_DB: pagila           # The default database to create
      POSTGRES_USER: pagila       # The default user to create
      POSTGRES_PASSWORD: postgres   # Password for the default user and postgres superuser
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - ./postgres_init:/docker-entrypoint-initdb.d:ro
      #- ./postgres_init/1.pagila-schema.sql:/docker-entrypoint-initdb.d/1.pagila-schema.sql
      - ./pg_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pagila -d pagila"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

#    networks:
#      - app_net

#volumes:
#  pg_data:
#    external: true

#networks:
#  app_net:
#    external: true

