## docker-compose.yaml

services:
  loki:
    image: grafana/loki:3.7.1
    container_name: loki
    restart: always

    volumes:
      - ./loki-local-config.yaml:/etc/loki/loki-local-config.yaml
      - ./loki_data:/tmp/loki    ## chown -R 10001:10001 loki_data

    command: -config.file=/etc/loki/loki-local-config.yaml

    ports:
      - "3100:3100"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      #- grafana_data:/var/lib/grafana
      - ./grafana_data:/var/lib/grafana   ## chown -R 472:472 grafana_data

    #user: "0"

    depends_on:
      - loki

    ports:
      - '3000:3000'
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:3.6.11
    container_name: promtail
    restart: always

    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      #- /var/log:/var/log:ro
      - /var/log/secure:/var/log/secure:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./positions:/tmp

    command: -config.file=/etc/promtail/promtail-config.yaml

    networks:
      - monitoring

    depends_on:
      - loki

#volumes:
#  grafana_data:
#  loki_data:

networks:
  monitoring:


