# Sample Logstash configuration for creating a simple
# Beats -> Logstash -> Elasticsearch -> Kibana pipeline.

input {
  file {
        path => ["/var/log/audit/audit.log", "/var/log/dnf.log"]
        #path => "/var/log/secure"
        #codec => "json"                #Or, rubydebug
        start_position => "beginning"   # For testing use
    }
}

output {
  elasticsearch {
    hosts => ["http://192.168.10.193:9200"]
    user => "elastic"
    password => "changeme"
    index => "ssh_secure-%{+YYYY.MM.dd}"
  }
}




