## promtail-config.yaml

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
  #- url: http://192.168.10.191:3100/loki/api/v1/push

scrape_configs:
## System journal / syslog
  - job_name: secure_log_host-193
    static_configs:
      - targets: [localhost]
        labels:
          job: secure_log_host-193
          __path__: /var/log/secure

## Docker container logs
#  - job_name: containers
#    static_configs:
#      - targets: [localhost]
#        labels:
#          job: containerlogs
#          __path__: /var/lib/docker/containers/*/*log
#    pipeline_stages:
#      - docker: {}



